tixy/urls.py
from django.conf.urls import url
from . import views

app_name = 'tixy'

urlpatterns = [
    # /tixy/
    url(r'^$', views.index, name='index'),

    # /tixy/<movie_id>/
    url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^book/(?P<slot_id>[0-9]+)/$', views.book, name='book'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^tixy/', include('tixy.urls')),
]

tixy/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Movie(models.Model):
    name = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    language = models.CharField(max_length=50)
    duration = models.CharField(max_length=50)
    pic = models.CharField(max_length=500)
    pic2 = models.CharField(max_length=500)

    def __str__(self):
        return self.name + ' (' + self.language + ') '


class Slot(models.Model):
    time = models.CharField(max_length=10)

    def __str__(self):
        return self.time


class Schedule(models.Model):
    slot = models.OneToOneField(Slot, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)

    def __str__(self):
        return self.movie.name + ' ' + str(self.slot)


class Booking(models.Model):
    class Meta:
        unique_together = (('slot', 'sno'),)

    slot = models.ForeignKey(Slot, on_delete=models.CASCADE)
    sno = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(20)],default=0)

    def __str__(self):
        return str(self.slot) + ' ' + str(self.sno)

tixy/views.py
from .models import Movie, Schedule, Slot, Booking
from django.shortcuts import render,redirect, get_object_or_404

def index(request):
    all_movies= Movie.objects.all()
    context = {'all_movies': all_movies,}
    return render(request, 'tixy/index.html', context)


def detail(request, movie_id):
    booking = Booking.objects.all()
    movie = get_object_or_404(Movie, id=movie_id)

    return render(request, 'tixy/detail.html', {'booking': booking,'movie': movie, 'all_shows': Schedule.objects.all(),})


def book(request, slot_id):
    slot = get_object_or_404(Slot, id=slot_id)
    seat = Booking(slot=slot)
    seat.save()

    return redirect('../../../admin/tixy/booking/' + str(seat.id) + '/change/', {'slot': slot})

tixy/templates/tixy/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Movie Details</title>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
      $( function() {
        $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
      } );
      </script>

</head>
<body>
    <div class="container">
      <div class="jumbotron">
        <h1>{{ movie.name }}</h1>
        <p>See details for your movie.</p>
        <img src="{{ movie.pic2 }}">
        <div class="row">
            <div class="col-md-4">
                <h2>Language: {{ movie.language }}</h2>
            </div>
            <div class="col-md-4">
                <h2>Genre: {{ movie.genre }}</h2>
            </div>
            <div class="col-md-4">
                <h2>Duration: {{ movie.duration }}</h2>
            </div>
        </div>

        <p>Available slots: </p>
      {% for show in all_shows %}
        {% if show.movie.id == movie.id  %}
            <div class="container">
                <div class="row">
                    <input type="button" value="{{ show.slot }}">
                </div>
            </div>
        {% endif %}
      {% endfor %}

        <br>

        <br>
        {% for show in all_shows %}
        {% if show.movie.id == movie.id  %}
        <form action="{% url 'tixy:book' show.slot.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Submit">
        </form>
        {% endif %}
        {% endfor %}
    </div>
    </div>
</body>
</html>

tixy/templates/tixy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Tixy- Holistic Movie Booking Platform</title>
</head>
<body>
    <div class="container">
      <div class="jumbotron">
        <h1>Tixy</h1>
        <p>Tixy is a holistic ticketing solution for any movie theatre</p>
      </div>
      <p>Select a movie to begin</p>
      <div class="row">
          {% for movie in all_movies  %}
          <div class="col-md-3">
              <a href="{% url 'tixy:detail' movie.id %}">
                  <img src="{{ movie.pic }}">
                  <div class="caption">
                      <p>{{ movie.name }}</p>
                  </div>
              </a>
          </div>
          {% endfor %}
      </div>
    </div>


</body>
</html>